name: e_cart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  velocity_x:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
